################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Source\ Files/dev_plat/tpos/low_power_tick_management.c \
../Source\ Files/dev_plat/tpos/sleep.c \
../Source\ Files/dev_plat/tpos/tpos_croutine.c \
../Source\ Files/dev_plat/tpos/tpos_heap_1.c \
../Source\ Files/dev_plat/tpos/tpos_list.c \
../Source\ Files/dev_plat/tpos/tpos_port.c \
../Source\ Files/dev_plat/tpos/tpos_queue.c \
../Source\ Files/dev_plat/tpos/tpos_tasks.c \
../Source\ Files/dev_plat/tpos/tpos_timers.c 

OBJS += \
./Source\ Files/dev_plat/tpos/low_power_tick_management.o \
./Source\ Files/dev_plat/tpos/sleep.o \
./Source\ Files/dev_plat/tpos/tpos_croutine.o \
./Source\ Files/dev_plat/tpos/tpos_heap_1.o \
./Source\ Files/dev_plat/tpos/tpos_list.o \
./Source\ Files/dev_plat/tpos/tpos_port.o \
./Source\ Files/dev_plat/tpos/tpos_queue.o \
./Source\ Files/dev_plat/tpos/tpos_tasks.o \
./Source\ Files/dev_plat/tpos/tpos_timers.o 

C_DEPS += \
./Source\ Files/dev_plat/tpos/low_power_tick_management.d \
./Source\ Files/dev_plat/tpos/sleep.d \
./Source\ Files/dev_plat/tpos/tpos_croutine.d \
./Source\ Files/dev_plat/tpos/tpos_heap_1.d \
./Source\ Files/dev_plat/tpos/tpos_list.d \
./Source\ Files/dev_plat/tpos/tpos_port.d \
./Source\ Files/dev_plat/tpos/tpos_queue.d \
./Source\ Files/dev_plat/tpos/tpos_tasks.d \
./Source\ Files/dev_plat/tpos/tpos_timers.d 


# Each subdirectory must supply rules for building sources it contributes
Source\ Files/dev_plat/tpos/low_power_tick_management.o: ../Source\ Files/dev_plat/tpos/low_power_tick_management.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32G280F128=1' -I"E:\test_restart0818\Collector_v1.0\Header Files\app_plat" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\flash" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\fun" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\tpos" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPRS" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPS" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\tpos\driver" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RS232" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\R8025T" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPIO" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/kits/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/kits/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/Device/SiliconLabs/EFM32G/Include" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/emlib/inc" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_APP" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_DB" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_MAC" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_MID" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_PROTOCOL" -O0 -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"Source Files/dev_plat/tpos/low_power_tick_management.d" -MT"Source\ Files/dev_plat/tpos/low_power_tick_management.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Source\ Files/dev_plat/tpos/sleep.o: ../Source\ Files/dev_plat/tpos/sleep.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32G280F128=1' -I"E:\test_restart0818\Collector_v1.0\Header Files\app_plat" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\flash" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\fun" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\tpos" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPRS" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPS" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\tpos\driver" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RS232" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\R8025T" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPIO" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/kits/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/kits/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/Device/SiliconLabs/EFM32G/Include" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/emlib/inc" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_APP" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_DB" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_MAC" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_MID" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_PROTOCOL" -O0 -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"Source Files/dev_plat/tpos/sleep.d" -MT"Source\ Files/dev_plat/tpos/sleep.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Source\ Files/dev_plat/tpos/tpos_croutine.o: ../Source\ Files/dev_plat/tpos/tpos_croutine.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32G280F128=1' -I"E:\test_restart0818\Collector_v1.0\Header Files\app_plat" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\flash" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\fun" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\tpos" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPRS" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPS" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\tpos\driver" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RS232" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\R8025T" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPIO" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/kits/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/kits/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/Device/SiliconLabs/EFM32G/Include" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/emlib/inc" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_APP" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_DB" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_MAC" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_MID" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_PROTOCOL" -O0 -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"Source Files/dev_plat/tpos/tpos_croutine.d" -MT"Source\ Files/dev_plat/tpos/tpos_croutine.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Source\ Files/dev_plat/tpos/tpos_heap_1.o: ../Source\ Files/dev_plat/tpos/tpos_heap_1.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32G280F128=1' -I"E:\test_restart0818\Collector_v1.0\Header Files\app_plat" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\flash" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\fun" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\tpos" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPRS" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPS" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\tpos\driver" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RS232" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\R8025T" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPIO" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/kits/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/kits/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/Device/SiliconLabs/EFM32G/Include" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/emlib/inc" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_APP" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_DB" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_MAC" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_MID" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_PROTOCOL" -O0 -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"Source Files/dev_plat/tpos/tpos_heap_1.d" -MT"Source\ Files/dev_plat/tpos/tpos_heap_1.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Source\ Files/dev_plat/tpos/tpos_list.o: ../Source\ Files/dev_plat/tpos/tpos_list.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32G280F128=1' -I"E:\test_restart0818\Collector_v1.0\Header Files\app_plat" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\flash" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\fun" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\tpos" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPRS" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPS" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\tpos\driver" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RS232" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\R8025T" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPIO" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/kits/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/kits/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/Device/SiliconLabs/EFM32G/Include" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/emlib/inc" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_APP" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_DB" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_MAC" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_MID" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_PROTOCOL" -O0 -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"Source Files/dev_plat/tpos/tpos_list.d" -MT"Source\ Files/dev_plat/tpos/tpos_list.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Source\ Files/dev_plat/tpos/tpos_port.o: ../Source\ Files/dev_plat/tpos/tpos_port.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32G280F128=1' -I"E:\test_restart0818\Collector_v1.0\Header Files\app_plat" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\flash" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\fun" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\tpos" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPRS" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPS" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\tpos\driver" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RS232" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\R8025T" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPIO" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/kits/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/kits/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/Device/SiliconLabs/EFM32G/Include" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/emlib/inc" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_APP" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_DB" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_MAC" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_MID" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_PROTOCOL" -O0 -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"Source Files/dev_plat/tpos/tpos_port.d" -MT"Source\ Files/dev_plat/tpos/tpos_port.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Source\ Files/dev_plat/tpos/tpos_queue.o: ../Source\ Files/dev_plat/tpos/tpos_queue.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32G280F128=1' -I"E:\test_restart0818\Collector_v1.0\Header Files\app_plat" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\flash" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\fun" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\tpos" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPRS" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPS" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\tpos\driver" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RS232" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\R8025T" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPIO" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/kits/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/kits/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/Device/SiliconLabs/EFM32G/Include" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/emlib/inc" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_APP" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_DB" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_MAC" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_MID" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_PROTOCOL" -O0 -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"Source Files/dev_plat/tpos/tpos_queue.d" -MT"Source\ Files/dev_plat/tpos/tpos_queue.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Source\ Files/dev_plat/tpos/tpos_tasks.o: ../Source\ Files/dev_plat/tpos/tpos_tasks.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32G280F128=1' -I"E:\test_restart0818\Collector_v1.0\Header Files\app_plat" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\flash" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\fun" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\tpos" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPRS" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPS" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\tpos\driver" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RS232" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\R8025T" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPIO" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/kits/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/kits/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/Device/SiliconLabs/EFM32G/Include" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/emlib/inc" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_APP" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_DB" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_MAC" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_MID" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_PROTOCOL" -O0 -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"Source Files/dev_plat/tpos/tpos_tasks.d" -MT"Source\ Files/dev_plat/tpos/tpos_tasks.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Source\ Files/dev_plat/tpos/tpos_timers.o: ../Source\ Files/dev_plat/tpos/tpos_timers.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32G280F128=1' -I"E:\test_restart0818\Collector_v1.0\Header Files\app_plat" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\flash" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\fun" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\tpos" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPRS" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPS" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\tpos\driver" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RS232" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\R8025T" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\GPIO" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/kits/common/bsp" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/kits/common/drivers" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/CMSIS/Include" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/Device/SiliconLabs/EFM32G/Include" -I"C:/SiliconLabs/SimplicityStudio/v3/developer/sdks/efm32/v2/emlib/inc" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_APP" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_DB" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_MAC" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_MID" -I"E:\test_restart0818\Collector_v1.0\Header Files\dev_plat\driver\RF\RF_PROTOCOL" -O0 -Wall -c -fmessage-length=0 -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"Source Files/dev_plat/tpos/tpos_timers.d" -MT"Source\ Files/dev_plat/tpos/tpos_timers.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


